### ISSUE TITLE
miniRT

### ISSUE THREAD

**Issue by JoLcte** [solaldunckel/miniRT#2]
Hello Solal, je voulais voir ton rendu de miniRT, mais au make j'ai bcp d'erreurs sur la libft notamment (variable unused, ...). Je voulais savoir si tu avais fait des mises a jour depuis ? Aussi, on ne peut pas compiler sur linux ?

**Comment by solaldunckel** [comment]
Hello,

Le projet a été fait sur les macs de l'école (avant l'obligation de travailler sur la VM) du coup en effet il est pas du tout fait pour compiler sur Linux (notamment a cause de la version de la MLX utilisé).
Je viens d'essayé de le compiler à 42, ça fonctionne toujours donc les problèmes de compilation libft sont spécifiques au gcc de Linux (les flags -Wall -Wextra -Werror sont beaucoup plus exigeant sur celle ci!).

**Comment by JoLcte** [comment]
Merci beaucoup pour ta réponse ! J’avais oublié que l’année dernière, tout se faisait à l’école haha
Ceci explique cela, je vais compiler sur Mac alors. Encore merci !
